# Exception Handling in Python
Exceptions are errors that occur during runtime, like dividing by zero ([_ZeroDivisionError_](https://docs.python.org/3/library/exceptions.html#ZeroDivisionError)); exceptions
can be managed through a process called exception handling. Exception handling allows you to deal with errors in a way that allows the program to continue running seamlessly 
(hopefully). Sometimes, an exception cannot be truly 'recovered' from, but can only be dealt with, in which case exception handing allows a more graceful solution to be achieved.

Exception handling uses four keywords: [_try_](https://www.w3schools.com/python/ref_keyword_try.asp), [_except_](https://www.w3schools.com/python/ref_keyword_except.asp), [_finally_](https://www.w3schools.com/python/ref_keyword_finally.asp), and [_raise_](https://www.w3schools.com/python/ref_keyword_raise.asp).

## Error Blocks with _try_..._except_

## Cleaning up with _finally_

## Manually Raising Errors with _raise_
